# Generated by Django 3.2.6 on 2021-09-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='update_ad',
            new_name='updated_ad',
        ),
    ]
