# Generated by Django 3.2.6 on 2021-09-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_update_ad_reviewrating_updated_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
